changelog.url=https://fixbrofficial.neocities.org/tomate/changelog
logo.url=https://github.com/FixBROfficial/testmods/blob/main/TOMATELOGO.png
mods.source.url=https://github.com/FixBROfficial/testmods/tree/main/mods
configs.source.url=https://github.com/FixBROfficial/testmods/tree/main/config
resourcepacks.source.url=https://github.com/FixBROfficial/testmods/tree/main/resourcepacks
initial.options.url=https://github.com/FixBROfficial/testmods/blob/main/options.txt
initial.servers.url=https://github.com/FixBROfficial/testmods/blob/main/servers.dat

minecraft.dir=${appdata}/.paradise
java.path=java
java.args=
minecraft.version=1.21.1
fabric.loader.version=0.19.3
fabric.profile=fabric-loader-0.19.3-1.21.1
mojang.version.manifest.url=https://piston-meta.mojang.com/mc/game/version_manifest_v2.json
fabric.profile.url=https://meta.fabricmc.net/v2/versions/loader/${minecraft.version}/${fabric.loader.version}/profile/json
game.width=854
game.height=480
quickplay.server=paradisecolorsrp.play.hosting

remove.unknown.mods=false
remove.unknown.configs=false
remove.unknown.resourcepacks=false
